### ISSUE TITLE
Serviceplatformen dynamic routing information 

### ISSUE THREAD

**Issue by rogtrifork** [trifork/klg-docs#11]
In order to successfully upload files onto **ext-test** of **serviceplatformen** we need to have a trigger file with specific information, however currently there is no single source of truth on the matter and as such we don't really know what to include in the individual fields thus the following questions **NEED** to be clarified:

1. Which **SENDER** do we need to use?
    * What to put in the `<Sender> </Sender>` field
2. What **SYSTEM** do we need to use and what is the **ID** of said system?
    * What to put in the `<SenderIt-system> </SenderIt-System` field
3. What is the **SENDER AUTHORITY** that we're supposed to use?
    * What to put in the `<SenderAuthority> </SenderAuthority>`
4. What is the **RECIPIENT AUTHORITY** that we're supposed to use?
    * What to put in the `<RecipientAuthority> </RecipientAuthority>` 

Here's an example of the XML that we currently send:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Trigger xmlns:ns2="http://serviceplatformen.dk/xml/wsdl/soap11/SFTP/1/types">
    <FileDescriptor>
        <FileName>test_data_1_2022-02-10.xml</FileName>
        <SizeInBytes>36</SizeInBytes>
        <Sender>FUT-Gateway</Sender>
        <Recipients>ROUTING_V1_0_0</Recipients>
    </FileDescriptor>
    <FileContentDescriptor>
        <SFTPDynamicRoutingInfo>
            <InfRef>Omsorgsdata_1</InfRef>
            <SenderIt-system>aff4e7d5-e35f-4021-b99f-e34593a678ff</SenderIt-system>
            <SenderAuthority>urn:oio:cvr-nr:19435075</SenderAuthority>
            <TransactionId>4a112a7d-1f6f-43ef-a364-7169bc5cb4d5</TransactionId>
            <SenderTimestamp>2022-02-10T13:46:37.632+01:00</SenderTimestamp>
            <RecipientAuthority>urn:oio:cvr-nr:19435075</RecipientAuthority>
        </SFTPDynamicRoutingInfo>
    </FileContentDescriptor>
</ns2:Trigger>
```
However, this produces:
```xml
<ns2:TechnicalReceipt xmlns:ns2="http://serviceplatformen.dk/xml/wsdl/soap11/SFTP/1/types">
    <FileTransferUUID>1ab09ad0-1eff-4eca-a99d-472c54e8c829</FileTransferUUID>
    <ErrorMessage>
        <ErrorCode>64</ErrorCode>
        <ErrorCodeDescription>RejectedNoSFTPForSendingItSystemFound</ErrorCodeDescription>
        <ErrorDescription>Error occurred while process trigger file. Contact Serviceplatformen Helpdesk. Transaction uuid: 1ab09ad0-1eff-4eca-a99d-472c54e8c829.</ErrorDescription>
    </ErrorMessage>
</ns2:TechnicalReceipt>
```

**Comment by jvitrifork** [comment]
@KirstenLHDK we would like to have Kombit/KL to provide the answer here

**Comment by 4TAMU** [comment]
Yes, correct

**Comment by jkiddo** [comment]
@4TAMU and what about the rest of the fields?
