### ISSUE TITLE
Client authentication with signed JWT failed: Token is not active

### ISSUE THREAD

**Issue by LindaLawton** [trifork/klg-docs#15]
I was getting access tokens twenty minutes ago.

# whats up?

**Comment by LindaLawton** [comment]
Its working again.  Now i am just curious to the cause of the issue.    

is this something i need to handle better in my code just keep trying until you return a token?

**Comment by nigtrifork** [comment]
Tis is propably due to clock skew. Try incessing the validity of your jws

**Comment by LindaLawton** [comment]
I believe we discussed this in a previous post I am using the following as per that post.

      Expires = DateTime.Now.AddSeconds(500),

**Comment by nigtrifork** [comment]
OK, you propably also have to account for clock skew in the other direction, by setting `nbf` and `iat` a few seconds back in time

**Comment by LindaLawton** [comment]
This seams reasonably stable at this point

                IssuedAt = DateTime.UtcNow.AddMinutes(-5),
                NotBefore = DateTime.UtcNow.AddMinutes(-5),
                Expires = DateTime.UtcNow.AddMinutes(5),  

Do you have any issues with those times?   I could boost it to ten minutes.  Yes i'm asking your opinion 😉

**Comment by nigtrifork** [comment]
yes this seems fine

**Comment by LindaLawton** [comment]
Unfortunately its not now i am getting forbidden.    I was making access tokens with this all morning now its failing again.
