### ISSUE TITLE
Access token request results in forbidden

### ISSUE THREAD

**Issue by LindaLawton** [trifork/klg-docs#16]
This same unit test was working all morning to return an access token .

Does anyone have a second to check your logs to figure out why I cant get access tokens anymore?

**Comment by LindaLawton** [comment]
I just tested again and im still getting the same error.   I have gone though the code that worked yesterday and I have changed nothing.    Its not the CVR number as we have double checked we have a service aftale with this kommune and if we didnt Kombit wouldnt give us a subject token

Anyone here to check this please??

@jkiddo  @nigtrifork @ohetrifork 


```
StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-store
  Date: Fri, 25 Feb 2022 07:36:06 GMT
  Pragma: no-cache
  Referrer-Policy: no-referrer
  Server: istio-envoy
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  x-b3-traceid: 3f78a3ade0b27a7a30e9d140d8b19d3f
  X-Content-Type-Options: nosniff
  x-envoy-upstream-service-time: 10
  X-Frame-Options: SAMEORIGIN
  X-Request-ID: 124b3e30-8c9c-4f52-89d5-c7783957d508
  X-XSS-Protection: 1; mode=block
  Connection: keep-alive
  Content-Type: application/json
  Content-Length: 78
}
```

**Comment by nigtrifork** [comment]
Hi @LindaLawton 

Can you change `subject_issuer` to `kombit-sts`, in stead of `kobit-sts`.

We corrected the typo yesterday, but the change was supposed to still allow `kobit-sts`, but apparrently it did not. Sorry for the inconvenience.

**Comment by LindaLawton** [comment]
You are my hero thank you so much!

I was bashing my head against this all after noon yesterday even rewrote my code (not bad idea really nice refactoring)
