### ISSUE TITLE
Questions regarding connecting to test environment

### ISSUE THREAD

**Issue by KirstenLHDK** [trifork/klg-docs#2]
Question from an EOJ-vendor
-	Hvilke Client ID og Client Secret vi skal bruge? 
-	Skal vi bruge en for hver kommune eller en enkelt for det hele?

**Comment by nigtrifork** [comment]
Hej

For at få adgang til Gateway skal der først oprettes en client til jer. Til det skal vi bruge den public key i bruger til Kombit STS. 
(På Test001 forventer vi at det er `https://adgangsstyring.eksterntest-stoettesystemerne.dk`). Det vil betyde 1 client pr kommune.

Når vi har modtaget public key opretter vi client og i vil derefter modtage et client id som i skal bruge.  Herefter følger i [vejledningen](https://github.com/trifork/klg-docs/blob/beb6e5e2b80b6647452278ef70e62b886cce6fc6/security-draft.md) for at få access tokens til Gateway.

I kan lægger jeres public key i dette repo under [clients](https://github.com/trifork/klg-docs/tree/main/clients), ved at lave en fork af repo og lave en pull request.

Bemærk at Test001 forventer at audience i SAML Assertion fra Kombit er `http://demo.prod-serviceplatformen.dk/service/DemoService/1`

**Comment by LindaLawton** [comment]
>Når vi har modtaget public key opretter vi client og i vil derefter modtage et client id som i skal bruge. Herefter følger i vejledningen for at få access tokens til Gateway.

1. Who should we send the keys to? 
2. how long can we expect it to take to get a client id returned? 
3. How will you be returning the client id?

>I kan lægger jeres public key i dette repo under clients, ved at lave en fork af repo og lave en pull request.

1. Am I to understand that you also want us to put our public keys in a public repo on github?  I know there public keys but this feels like a bad idea to me.
2. Will you also be putting our private client id and secrets in the repo?
3. Isn't there a secure email address we can send these requests to?

**Comment by KirstenLHDK** [comment]
@nigtrifork will you please help

**Comment by jvitrifork** [comment]
Regarding
> 1. Who should we send the keys to?

They should be part of the PR

Regarding
> 1. Am I to understand that you also want us to put our public keys in a public repo on github?  I know there public keys but this feels like a bad idea to me.

regarding public keys: see https://security.stackexchange.com/questions/150540/is-it-completely-safe-to-publish-an-ssh-public-key

Regarding
> 3. Isn't there a secure email address we can send these requests to?

Preferrably not
> 

Regarding
> Note: this page does not work https://adgangsstyring.eksterntest-stoettesystemerne.dk
> 
> ![image](https://user-images.githubusercontent.com/6592543/147915576-580a1aad-4200-4942-b47a-520cdec0678a.png)
> 
it is the value of the audience - it is not intended to necessarily resolve


> @KirstenLHDK do you know what `Til det skal vi bruge den public key i bruger til Kombit STS` could be?

**Comment by nigtrifork** [comment]
> @KirstenLHDK do you know what `Til det skal vi bruge den public key i bruger til Kombit STS` could be?

It is the public key of the key-pair a client uses to obtain the SAML Assertions from the Kombit STS.  I has to be the same key, in order to validate that the client is 'holder of key', i. e. that the SAML Assertion was indeed issued to that specific client.

**Comment by jvitrifork** [comment]
@LindaLawton we can offer you a brief video meeting if you would like that. Let us know if that is something we should set up

**Comment by LindaLawton** [comment]
@jvitrifork  that would be really nice if you have time.  

I think my main issue at this point is understanding where I'm supposed to apply to get this Kombit STS private key file.  To send to you so that I can get the client id setup

I am currently trying to get the JWT to work from the sample you gave and I mentioned in my other question.   I'm currently getting invalid signature JWT.IO  but I think I'm close.  I'm pretty sure the issue is in the header

**Comment by jvitrifork** [comment]
Which vendor are you working on behalf of?

**Comment by LindaLawton** [comment]
I'm a freelance consultant for KMD

**Comment by aonsystematic** [comment]
if you are having a meeting please post the result here as well, to my understanding the private/public key is the certificate on an it-system on serviceplatformen. But it would be nice to have it clarified, since the documentation seems to assume that the vendor is familiar with kombit and fut already.

**Comment by jvitrifork** [comment]
@aonsystematic you are welcome to join the meeting as well

**Comment by aonsystematic** [comment]
yes, I would like that

**Comment by jvitrifork** [comment]
Great @nigtrifork will get back to you both

**Comment by aonsystematic** [comment]
when can we expect to hear more, our release schedule is somewhat tight.

**Comment by nigtrifork** [comment]
Hi @aonsystematic 

I need to gather some more information from Kombit, before a meeting would makes sense. Until then, I would suggest to check out [this discussion](https://github.com/trifork/klg-docs/issues/3) and start working on the client authentication part.

**Comment by LindaLawton** [comment]
@nigtrifork any update on this.  We still need some documentation on 

     subject_token: The Base64url encoded SAML Assertion issued by subject_issuer

Even the .net out of date .net example doesn't show how its created [Demoservice-client-net/search?q=subject_token](https://github.com/Serviceplatformen/demoservice-client-net/search?q=subject_token)

**Comment by nigtrifork** [comment]
Documentation is here:

https://digitaliseringskataloget.dk/l%C3%B8sninger/adgangsstyring-systemer
https://digitaliseringskataloget.dk/files/integration-files/161120201010/Programmers%20Guide%20-%20Sikkerhed%20i%20den%20f%C3%A6lleskommunale%20infrastrukturen.pdf

the class you are looking for is here https://github.com/Serviceplatformen/demoservice-client-net/blob/94e1383cebd14b8f3c24f490a8c8b48b77869661/DemoTokenClient/DemoTokenClient/Token/TokenFetcher.cs#L13

**Comment by LindaLawton** [comment]
I'm I to understand that this isn't just out of date documentation.  That you are using a soap webservice for authorization?

**Comment by nigtrifork** [comment]
Yes, that is correct.

**Comment by LindaLawton** [comment]
Do you have the Webservice endpoint the only thing I can find in that project is a [wsdl](https://github.com/Serviceplatformen/demoservice-client-net/search?q=wsdl) file with a bunch of http endpoints.  None of them will load.

I need an endpoint so I can add the webservice reference.

**Comment by nigtrifork** [comment]
https://adgangsstyring.eksterntest-stoettesystemerne.dk/runtime/services/trust/14/certificatemixed

found here: https://digitaliseringskataloget.dk/l%C3%B8sninger/adgangsstyring-systemer

**Comment by LindaLawton** [comment]
The last link is priceless You should add that to your documentation.    Along with a note that the subject_token is created via the Soap webservice.

Sadly that endpoint isn't right either.

![image](https://user-images.githubusercontent.com/6592543/149766070-0aa55fff-52cb-40cf-a6dc-062249efbe77.png)

**Comment by LindaLawton** [comment]
@aonsystematic  what language are you trying to do this in?   I have never thing working with .net except the subject_token which comes from Kombit via a web service.  

Im happy to write you a little tutorial on what i have done so far.   I can get as far as an access token.  Just wont get a refresh token.

**Comment by aonsystematic** [comment]
we use java, but if the steps are well documented I can probably figure it out no matter what language it is.

But it seems to me, that we are both stuck at the same spot, by being unable to get a token from kombit STS.
The steps that come after that in the flow (creating the JWT and calling the keycloak) I have, but I am unable to validate without the kombit token, which is used to authenticate, when calling the keycloak

Another thing I was wondering was what exactly the public key we should upload here is, my current best guess is that it is the public part of the function certificate on serviceplatformen.

**Comment by jvitrifork** [comment]
See https://github.com/trifork/klg-docs/issues/3#issuecomment-1015284562 for getting access to Kombit STS

**Comment by aonsystematic** [comment]
> See [#3 (comment)](https://github.com/trifork/klg-docs/issues/3#issuecomment-1015284562) for getting access to Kombit STS

that wouldn't explain what entityId we should use since that is domain specific, and when I checked on serviceplatformen, last time there were no gateway service listed there, from what I could find.
I already have a working example of getting connection to the "kombit beskedfordeler" but I cannot use that entityId (which is http://beskedfordeler.eksterntest-stoettesystemerne.dk/service/afhent/1) again, since the gateway service is unrelated to that.

**Comment by LindaLawton** [comment]
@aonsystematic I used the p12 file from the sample project and extracted the public key file from that.  We need to get the p12 cert from Kombit STS apparently which we can then get the P12

@jvitrifork How can you be using a system that you cant support yourselves.  Why aren't you using your own identity server for this?

**Comment by jvitrifork** [comment]
It's a federated setup - we trust the Kombit IdP. It's a pretty normal setup to have a federated setup.

**Comment by jvitrifork** [comment]
The entityId that you can use is `http://ehealth.sundhed.dk/service/CareGateway/1` - documentation will be updated with this tomorrow

**Comment by LindaLawton** [comment]
@jvitrifork  my previous experience with federated identity providers is just that with identity providers.  Its normally very strait forward to set up almost plug and play.   However we are not trying to authorize a user here.  We are just trying to authenticate access to an api end point.  This isn't open id connect, this isn't signin.   

May I has have you ever worked with a system that does not fully document their authorization flow but instead directs the users of their system to go contact another company?   Please just fully document this and not forward us to Kombit STS, its been a month.    I still cant connect to the web service you say i should be using.  If i should be using it why is it resulting in a 400 error.    

Is this the authorization method you plan on using and its just not live yet?  is that why its not fully documented and we cant access it?

**Comment by jvitrifork** [comment]
The term `Identity Provider` is not limited to OICD. See ie. https://en.wikipedia.org/wiki/Identity_provider#Types_of_identity_providers

**Comment by LindaLawton** [comment]
I have another one for you 

https://www.oauth.com/oauth2-servers/openid-connect/authorization-vs-authentication/

**Comment by aonsystematic** [comment]
ok I have now found the service and I'm trying to setup a service agreement, can you help telling me which UUID I should put in the marked area in the picture below. I assume it's the organization that owns the data, but it is not clear. Especially since the "Care Gateway" service does not appear to be listed here https://digitaliseringskataloget.dk/services
![image](https://user-images.githubusercontent.com/97035354/150125372-2daa011b-c44f-4e6f-98e5-c4e8542883ca.png)

**Comment by nigtrifork** [comment]
@aonsystematic  

> I assume it's the organization that owns the data, but it is not clear. 

yes, that is correct, the sts-org id.

The service was created on test yesterday, It is not on production yet

**Comment by LindaLawton** [comment]
@aonsystematic  what page is that image from?

**Comment by aonsystematic** [comment]
> The service was created on test yesterday, It is not on production yet

it is https://admin-test.serviceplatformen.dk/ you likely need help from your it department to get access though

**Comment by LindaLawton** [comment]
@aonsystematic yeah this is not something i will have permission to access if it requires nemid.  

Im trying to connect a microservice here not a user why does this even need nemid?

**Comment by KirstenLHDK** [comment]
@aonsystematic - I have a list of UUIDs for municipalities in test. Please contact me at khansen@deloitte.dk and I will share it

**Comment by aonsystematic** [comment]
> @aonsystematic
> 
> > I assume it's the organization that owns the data, but it is not clear.
> 
> yes, that is correct, the sts-org id.
> 
> The service was created on test yesterday, It is not on production yet

another question should "myndighed" be the municipality (the one I just set as UUID) or KOMBIT. We were thinking it could be KOMBIT since the Care Delivery Reporter already points to the municipality

**Comment by nigtrifork** [comment]
@aonsystematic 
> another question should "myndighed" be the municipality (the one I just set as UUID) or KOMBIT. We were thinking it could be KOMBIT since the Care Delivery Reporter already points to the municipality

Data owner should be the municipality, data receiver should be Kombit

**Comment by nigtrifork** [comment]
@LindaLawton 

> nigtrifork am i to understand from that statement that this isn't even live yet?

The test environment "test001" is live. Production is not live yet.

**Comment by aonsystematic** [comment]
> @aonsystematic
> 
> > another question should "myndighed" be the municipality (the one I just set as UUID) or KOMBIT. We were thinking it could be KOMBIT since the Care Delivery Reporter already points to the municipality
> 
> Data owner should be the municipality, data receiver should be Kombit

ok, in that case what kind of "serviceaftaletype" do I have to pick? I assume it would have to be "Med videregivelse af data, én dataejer og én datamodtager"

**Comment by nigtrifork** [comment]
> > @aonsystematic
> > > another question should "myndighed" be the municipality (the one I just set as UUID) or KOMBIT. We were thinking it could be KOMBIT since the Care Delivery Reporter already points to the municipality
> > 
> > 
> > Data owner should be the municipality, data receiver should be Kombit
> 
> ok, in that case what kind of "serviceaftaletype" do I have to pick? I assume it would have to be "Med videregivelse af data, én dataejer og én datamodtager"

yes

**Comment by aonsystematic** [comment]
> > > @aonsystematic
> > > > another question should "myndighed" be the municipality (the one I just set as UUID) or KOMBIT. We were thinking it could be KOMBIT since the Care Delivery Reporter already points to the municipality
> > > 
> > > 
> > > Data owner should be the municipality, data receiver should be Kombit
> > 
> > 
> > ok, in that case what kind of "serviceaftaletype" do I have to pick? I assume it would have to be "Med videregivelse af data, én dataejer og én datamodtager"
> 
> yes

thank you, hopefully this is the last question. You mention that the public key we upload on this page is the one we use for kombit sts. So just that we are clear, this is referring to the public part of the function certificate that is uploaded on our it-system in "anvender system"

![image](https://user-images.githubusercontent.com/97035354/150335198-37ec6c55-fda9-46e0-9109-653649b85461.png)

**Comment by nigtrifork** [comment]
exactly

**Comment by aonsystematic** [comment]
> exactly

ok, this is however a certificate (used for ssl) and not a public key (used for pgp), are you fine with us uploading a ".cer" file of the form:
-----BEGIN CERTIFICATE-----
contents....
-----END CERTIFICATE-----

or do you want me to just edit it so it says:
-----BEGIN PUBLIC KEY-----
contents...
-----END PUBLIC KEY-----

followed by changing the extension to ".pub", so that it is like the example

**Comment by nigtrifork** [comment]
.cer is fine

**Comment by LindaLawton** [comment]
I have come a little farter  Can you answer this question for me.   I am trying to get access to this system.

>Hvilken snitflade skal i benytte på https://digitaliseringskataloget.dk/ ?
