### ISSUE TITLE
DUPLICATE_ENTITY:

### ISSUE THREAD

**Issue by LindaLawton** [trifork/klg-docs#20]
This is our first attempt at running.  I'm curious as to where the DUPLICATE_ENTITY is coming from.

```
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "DUPLICATE_ENTITY: Entity with id \u0027Bundle/9866EBF2-6A1E-4EC6-BCC0-1449BF741ECA\u0027 already exists"
    }
  ]
}
```

We will be testing this over the next month.  I hope your Test server will be able to handle us sending requests more then once in a day.

**Comment by ohetrifork** [comment]
Hi Linda. The DUPLICATE_ENTITY error you are receiving happens when a CareDeliveryReport with that ID ("9866EBF2-6A1E-4EC6-BCC0-1449BF741ECA" in this case) has already been created in KLG. Every new CareDeliveryReport must have a unique UUID, so if you generate a new UUID, you should not receive that error.

**Comment by ohetrifork** [comment]
I just added a small "Errors" section, which also describes the DUPLICATE_ENTITY error. Thanks for pointing that one out.

https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2189361157/Care+Gateway#Error-messages

**Comment by LindaLawton** [comment]
@ohetrifork  thanks for the clarification.  I loaded the same data in to my que twice for testing.  That's why the GUID was the same.   In testing this is going to be hard to avoid as the database is generated for me once and I just resend the data.   I will have to see if i can come up with a hack for testing.
