### ISSUE TITLE
Condition - Encounter som en-til-mange relation

### ISSUE THREAD

**Issue by MikaelKorsgaard** [trifork/klg-docs#22]
Modellen ser ikke ud til at supportere, at en condition kan have flere encounters (opfølgninger). Vi bruger extension (KLGatewayCareFollowUpEncounterExtension) via condition til at lave relationen mellem condition og encounter, men får nedenstående fejl, når en condition er relateret til flere (historiske) opfølgninger. 

"
   "severity": "error",
    "code": "processing",
    "diagnostics": "Condition.extension:followUpEncounter: max allowed = 1, but found 3 (from http://gateway.kl.dk/1.0/StructureDefinition/klgateway-care-condition)",
    "location": [ "Bundle.entry[4].resource.ofType(Condition)", "Line 218, Col 21" ]
"

Er I kun interesseret I at få den seneste Encounter?

**Comment by LindaLawton** [comment]
I have put up a Gist with the report we are sending and the response we are getting.

[KlFhirIssueOneReport and response](https://gist.github.com/LindaLawton/ea4c8777c3db517523aaee3316a0ef85#file-klfhirissueonereport-json)](https://gist.github.com/LindaLawton/ea4c8777c3db517523aaee3316a0ef85)

**Comment by jkiddo** [comment]
@MikaelKorsgaard - Det er tanken at det er det er den næste opfølgning, der sendes med. Eftersom der indberettes dagligt vil der komme en ny rapportering, når opfølgningen er sket og en ny dato er sat. Dette er valgt ud fra kriteriet at rapporteringen er de aktuelle data på indberetningstidspunktet.

**Comment by MikaelKorsgaard** [comment]
@jkiddo Ja, det slog mig også efter vores dialog om daglige rapporter, at det dermed ikke ville være et issue længere.
