### ISSUE TITLE
Documentation confusion Encounter.type.coding  vs Encounter.type.coding.code

### ISSUE THREAD

**Issue by LindaLawton** [trifork/klg-docs#24]
[Resource Profile: CareEncounter](https://build.fhir.org/ig/hl7dk/kl-gateway/StructureDefinition-klgateway-care-encounter.html)

If we read first this part.

>It is important in FSIII to be able to express follow-up encounters. In the planning state, these are documented by setting Encounter.status = “planned”, and Encounter.type.coding = “opfølgning”. When a followUp has been performed, the Encounter.status is changed to “finished”.

Then we check the model.

![image](https://user-images.githubusercontent.com/6592543/159004122-8db7a428-8a0d-45df-a03b-cc0de5efd2fd.png)

Not only does the model not match Encounter.type.coding but type.coding.code is a fixed value.

**Comment by jkiddo** [comment]
Planning state:

```
Encounter.status = 'planned'
Encounter.type.coding.code = '9f03dfbb-7a97-45a5-94db-d4c3501714a9'
```

Follow-up:
```
Encounter.status = 'finished'
Encounter.type.coding.code = '9f03dfbb-7a97-45a5-94db-d4c3501714a9'
```


Wherein lies the confusion?

**Comment by LindaLawton** [comment]
The first one `Encounter.type.coding = “opfølgning”` has a value that is a string.

Yet the json shows `Encounter.type.coding`  is an object.    

Even in your example you are setting it to `Encoutner.type.coding.code` which is again an object and you are not setting Encounter.type.coding = “opfølgning” to a string.

**Comment by jkiddo** [comment]
Consider the following as pseudo code

```
Encounter.status = 'finished'
Encounter.type.coding.code = '9f03dfbb-7a97-45a5-94db-d4c3501714a9'
```

For datatype binding questions specific for the language C# please refer to eg. https://www.nuget.org/packages/Hl7.Fhir.R4

**Comment by LindaLawton** [comment]
Consider this line. 

Encounter.type.coding = “opfølgning”    

How do I set 

Encounter.type.coding equal to a string. 

We are following the guidelines defined for this this project eg. [Resource Profile: CareEncounter](https://build.fhir.org/ig/hl7dk/kl-gateway/StructureDefinition-klgateway-care-encounter.html)  Please refer to the model shown there.

**Comment by jkiddo** [comment]
Looking at https://build.fhir.org/ig/hl7dk/kl-gateway/Encounter-bfa70a76-318d-453d-9abc-76982f8d13ca.json.html - which is 

```json

{
  "resourceType": "Encounter",
  "id": "bfa70a76-318d-453d-9abc-76982f8d13ca",
  "meta": {
    "profile": [
      "http://gateway.kl.dk/1.0/StructureDefinition/klgateway-care-encounter"
    ]
  },
  "status": "planned",
  "class": {
    "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
    "code": "HH"
  },
  "type": [
    {
      "coding": [
        {
          "system": "http://kl.dk/fhir/common/caresocial/CodeSystem/KLCommonCareSocialCodes",
          "code": "9f03dfbb-7a97-45a5-94db-d4c3501714a9"
        }
      ]
    }
  ],
  "subject": {
    "reference": "Patient/TestPerson"
  },
  "period": {
    "start": "2020-08-14"
  }
}
``` 

-the Encounter.type.coding.code `9f03dfbb-7a97-45a5-94db-d4c3501714a9` is bound to the social codes here: https://build.fhir.org/ig/hl7dk/KL-dk//CodeSystem-KLCommonCareSocialCodes.html - where you can see that `9f03dfbb-7a97-45a5-94db-d4c3501714a9` translates to "opfølgning". Meaning: you set the coded value, not the text.

**Comment by LindaLawton** [comment]
>where you can see that 9f03dfbb-7a97-45a5-94db-d4c3501714a9 translates to "opfølgning".

So the text is an error and the json is correct?   Thank you that's all I needed verified.
