### ISSUE TITLE
DeliveryReport - opdatering eller nyt id hver gang

### ISSUE THREAD

**Issue by shejgaardkriDedalus** [trifork/klg-docs#25]
Vi er ikke helt sikre på, hvordan vi skal forstå "_The id of any resource must be universally unique, e.g. a uuid. Resources with the same id as previously reported are considered to be an update of the previous reported information at the time indicated in the metadata of the resource._" fra IG'en. Vi forstod det egentligt som om, at når der sker en ændring/opdatering i information om en bestemt borgers indsatser, så vil vi skulle sende en delivery report med samme id som den tidligere version af denne borgers delivery report, så det på gatewayen bliver set som en update. Men [her](https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2189361157/Care+Gateway#Business-Flow) kan vi se, at der sendes flere delivery reports med forskellige id'er for samme borger. 

Hvad er den rigtige tilgang? Er det opdateringer af allerede indberettede delivery reports (samme Bundle.id) eller nye delivery reports (nyt Bundle.id)? Og hvis man laver nye delivery reports for hver borger, er der så stadig situationer hvor man vil lave en opdatering, og hvad er disse situationer?

**Comment by LindaLawton** [comment]
Jeg ved ikke om det er rigtigt eller ej men vi sender altid en ny bundle id.   

Jeg kan også se at hvis du sender de samme bundle id mere en en gang om dagen så få du en **DUPLICATE_ENTITY** fejl.   Så jeg tror ikke det er en update.    bundle id + dato må være en primary key af en eller anden art.

**Comment by ohetrifork** [comment]
Hej Signe. 
Formuleringen, du henviser til, er et levn fra tidligere, og er beklageligvis ikke blevet ajourført ifm. nærmere aftaler omkring API'ets anvendelse. Der understøttes ikke opdateringer på Bundle-niveau, hvor det nu er et krav, at der indsendes nyt Bundle.id for hver ny indsendelse (PUT) - også selvom det logisk set er en opdatering. Den efterfølgende konsolidering af data sker i systemerne, der aftager data på "bagsiden" af KLG.
Mvh. Ole Hedegaard

**Comment by shejgaardkriDedalus** [comment]
Hej Ole, 
Super - mange tak for afklaringen.
