### ISSUE TITLE
Encounter - versionering

### ISSUE THREAD

**Issue by shejgaardkriDedalus** [trifork/klg-docs#26]
Vi kan i indberetningsvejledningen og i IG'en læse, at den Encounter, der skal sendes med altid er den **næste** opfølgningskontakt på en tilstand.
Betyder det, at når en opfølgningskontakt er gennemført, så skal vi ikke længere sende den med? I IG'en under Encounter står der, at Encounter.status skal skiftes til "finished", når opfølgningen er gennemført - men det har ikke så meget effekt at ændre status'en, hvis vi alligevel ikke skal sende den Encounter-instans. Skal en gennemført Encounter nogle gange sendes med, og i så fald: i i hvilke situationer?

**Comment by hagensen-software** [comment]
Jeg er ikke længere på projektet men svarer lige med den intension der ligger bag :-)

FSIII kræver blot registrering af næste opfølgningsdato, så derfor skal man sende dette med som en fremtidig encounter. En gennemført opfølgning vil være repræsenteret i en follow-up observation og gennemførte encounters skal ikke rapporteres.

**Comment by shejgaardkriDedalus** [comment]
Hej Torben 
Tak for svar :-) Det giver fin mening.

Måske dokumentationen omkring, at status ved en udført opfølgning skal sættes til 'finished' skal ændres, hvis det aldrig er tilfældet.

**Comment by jkiddo** [comment]
@shejgaardkriDedalus er det denne her section du tænker på?

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/211696/165104615-2baea38e-82b4-4fac-b119-852d561f4124.png">

**Comment by shejgaardkriDedalus** [comment]
@jkiddo Ja, lige præcis.

**Comment by jkiddo** [comment]
Så en ændring fra `When a followUp has been performed, the Encounter.status is changed to "finished"` ændres til `Encounters which are finished should not be reported hence Encounters with Encounter.status = 'finished' should not be reported and can be omitted entirely`. Stemmer det overens med forståelsen fra FSIII, @hagensen-software ?

**Comment by hagensen-software** [comment]
Det vil passe fint med forståelsen i FSIII og matcher også med at profileringens referencer til encounter har kardinaliteten 0..1, hvilket ikke vil være nok hvis man både skal sende en 'finished' og en ny næste opfølgning.

**Comment by jkiddo** [comment]
Rettet til med https://github.com/hl7dk/kl-gateway/commit/98dea7a47909948e345b09f85a00000cbb53e8ba
