### ISSUE TITLE
Condition.Status change to potential

### ISSUE THREAD

**Issue by MikaelKorsgaard** [trifork/klg-docs#27]
En tilstand skifter mellem aktiv og inaktiv, men den kan også skifte til potentiel. Hvordan håndterer jeg denne status ændring i condition, når en potentiel indsats skal indberettes i MatterOfInterestObservation?

**Comment by hagensen-software** [comment]
Jeg er ikke længere på projektet men svarer lige med den intension der ligger bag :-)

FSIII skelner mellem områder og tilstande, så et skifte fra aktiv til potentiel vil svare til at den pågældende condition ikke længere er aktiv og der opstår en matter of interest. Tilsvarende den anden vej.

**Comment by MikaelKorsgaard** [comment]
Tak Torben. Så i tilfældet hvor en tilstand skifter fra aktiv til potentiel indberetter jeg både, at tilstanden går i inaktiv, og at vi har en ny potentiel tilstand (med reglerne for MatterOfInterestObservation in mente)?

**Comment by hagensen-software** [comment]
Ja, det skulle jeg mene :-)

**Comment by shejgaardkriDedalus** [comment]
Lige et opfølgende spørgsmål: Vi indberetter borgervurdering, der kobles til tilstandsområdet, og derfor rapporterer vi allerede tilstandsområdet, når en tilstand er aktiv. Er det rigtigt forstået, at hvis tilstanden og tilstandsområdet skifter til potentiel, at vi skal sende et nyt tilstandsområde? Er det så muligt at skelne mellem, om et tilstandsområde er aktivt eller potentielt?

**Comment by hagensen-software** [comment]
Fortolkningen på gateway'en lægger sig op af FS3. Ifølge FS3 dokumenteres aktuelle problemer på tilstande og ikke tilstandsområder, så et tilstandsområde vil være at betragte som aktuelt hvis der er indberettet tilstande (under tilstandsområdet). Tilstandsområdet vil derfor ikke blive påvirket medmindre det ikke længere er relevant.
