### ISSUE TITLE
PlannedIntervention.Status, PlannedIntervention.ActivityStatus

### ISSUE THREAD

**Issue by MikaelKorsgaard** [trifork/klg-docs#28]
I PlannedIntervention skal vi indberette hhv. "indsatsstatus" og "indsatsAktivitetsstatus". Vi har læst beskrivelserne, men vi er statig i tvivl om, hvordan de adskiller sig. Eksemplerne viser kun "active" og "completed" for "indsatsstatus", imens alle eksempler med "indsatsAktivitetsstatus" viser "in-progress". 

Vil I uddybe (evt. ved hjælp af eksempler), hvordan vi skelner mellem de to statusser?

**Comment by hagensen-software** [comment]
Jeg er ikke længere på projektet men svarer lige med den intension der ligger bag :-)

Eftersom intervention og activity.detail er 1..1 vil det være oplagt at status på disse sættes til det samme. Hvis du kigger på definition for de to felter vil du også se at beskrivelserne er identiske. Felterne skal begge være der fordi de er påkrævede i FHIR ressourcen. (... og ja det kunne godt have været gjort i eksemplerne og evt. sat på som en constraint :-| )

**Comment by MikaelKorsgaard** [comment]
Tak! Jeg kom i tvivl, da oversættelse mellem dansk (KL) og FHIR i 5.10.1.2 (Conversions between Danish information model and FHIR-profile) for de to statusser netop ikke er enslydende. Den ene taler om indsatsplan og den anden om indsats. 

Vi sætter det til det samme.

**Comment by shejgaardkriDedalus** [comment]
Måske misforstår jeg denne samtale, men udfaldsrummene for PlannedIntervention.status og PlannedIntervention.activity.detail.status er da ikke ens, så det er vel ikke muligt at sætte dem til det samme?

**Comment by MikaelKorsgaard** [comment]
Enig, @shejgaardkriDedalus. For nu har jeg hhv. status og activitystatus til:

- active / in-progress
- on-hold / on-hold
- completed / completed
- revoked / cancelled

**Comment by jkiddo** [comment]
@MikaelKorsgaard - mangler du forsat svar?

**Comment by MikaelKorsgaard** [comment]
@jkiddo Nej den lukker du bare.
