### ISSUE TITLE
Genaktivering af tilstande og tilstandsområder

### ISSUE THREAD

**Issue by shejgaardkriDedalus** [trifork/klg-docs#29]
I indberetningsvejledningen og IG'en står beskrevet, at tilstande opdateres, når de skifter status fra aktiv til inaktiv, og at tilstandsområder opdateres til value = 'ikke relevant', når de ikke længere er i fokus. 
Hvordan skal vi håndtere det, hvis det modsatte sker, og de genaktiveres? 
- Altså hvis en tilstand er afsluttet og efterfølgende startes igen (med samme kode som tidligere)? Skal det betragtes som en ny tilstand over for gatewayen med nyt id, eller skal det være en opdatering af den tidligere tilstand? 
- Eller hvis et tilstandsområde er markeret med 'ikke relevant' og bliver relevant igen efterfølgende? Skal det betragtes som et nyt tilstandsområde over for gatewayen med nyt id, eller skal det være en opdatering af den tidligere tilstand?

**Comment by hagensen-software** [comment]
Hvis en tilstand startes igen vil jeg mene at den enten kan betragtes som en ny tilstand eller en opdatering af en afsluttet tilstand. Begge dele burde være ok

Hvis et tilstandsområde er "ikke relevant" og genoptages kan det efter min mening også være ok at oprette et nyt område eller opdatere det afsluttede. Det kan i sagens natur ikke være en opdatering af en tilstand.
