### ISSUE TITLE
KL-Gateway FHIR Implementation Guide (IG) ikke tilgængelig

### ISSUE THREAD

**Issue by MikaelKorsgaard** [trifork/klg-docs#33]
Det lader til, at http://build.fhir.org/ig/hl7dk/kl-gateway/ er nede. Vil I kigge på det?

**Comment by KirstenLHDK** [comment]
Fundet, og fejlrettelse er i gang. @jkiddo opdaterer, når IG igen er tilgængelig.

**Comment by jkiddo** [comment]
IG'en er oppe igen

**Comment by LindaLawton** [comment]
@jkiddo  thank you for fixing this.
