### ISSUE TITLE
SAML Assertion to JWT Exchange - Production endpoint

### ISSUE THREAD

**Issue by LindaLawton** [trifork/klg-docs#40]
[SAML Assertion to JWT Exchange](https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2187362305/SAML+Assertion+to+JWT+Exchange) points to 

    https://saml.test001.ehealth.sundhed.dk

Do you have the production endpoint?

**Comment by LindaLawton** [comment]
@nigtrifork  can i assume that the gateway address will then be

Gateway: https://care-gateway.prod001.ehealth.sundhed.dk

**Comment by jkiddo** [comment]
@LindaLawton are you good with the answer?

**Comment by LindaLawton** [comment]
@jkiddo  we have made our first call to production I can verify that this endpoint is working perfectly.  No issues at all from our end.  Data is being sent.  

Thanks for everything.

**Comment by jkiddo** [comment]
@LindaLawton we can confirm we have recieved the submission and it has continued its flow as far as expected in the system complex. Tonight we'll know if the last batch part works as intended. We'll keep you posted tomorrow.
