### ISSUE TITLE
Production client id

### ISSUE THREAD

**Issue by LindaLawton** [trifork/klg-docs#42]
Should i assume we are using the same client id in production.

This is what we are using currently in tests:  `kmd-nexus-test`   given to us in [#12](https://github.com/trifork/klg-docs/pull/12)

No mention of a new client id in [37](https://github.com/trifork/klg-docs/pull/37)

**Comment by nigtrifork** [comment]
Hi @LindaLawton 

your client id for production is `kmd-nexus-prod`
