### ISSUE TITLE
CarePlan - level3 koder

### ISSUE THREAD

**Issue by MaleneLarsen** [trifork/klg-docs#45]
Vi har tidligere fået afklaret på Zulip, at der skal oprettes nye instanser af CarePlan for hver level3 kode, fordi modellen kun kan indeholde én level3 kode i hver CarePlan instans (https://chat.fhir.org/#narrow/stream/274483-denmark.2Fkl.2Fprofile.2Fkl-gateway/topic/Multiple.20level.203.20interventions) 

Men vi har et par spørgsmål til, hvordan level3 koderne skal håndteres i indberetningen. 

- Hvis en level3 kode registreres senere end level2 koden og vi indsender en ny instans af CarePlan med level 3 koden og den tilhørende level2 kode, hvilket tidspunkt forventer I så at modtage i period.start for den nye instans? Er det samme tidspunkt som for level2 koden, fordi det tilsvarer tidspunktet for, hvornår indsatsen er bevilget?

- Hvis level3 koden afsluttes inden level2 koden (indsatsen) afsluttes, hvordan skal CarePlan instansen, hvor level3 koden er indeholdt, så opdateres?

- Hvis der er registreret en level2 kode og en level3 kode på samme tid, så indsender vi altid to instanser af CarePlan: level2 koden i én instans (uden level3 koden) og level3 koden i en anden instans. Vi gør det for at have mulighed for at opdatere level3 kode instansen, uden at det påvirker level2 kode instansen, sådan at level2 kode instansen kan fortsætte, selvom level3 koden afsluttes. Stemmer det overens med det I forventer?

**Comment by jkiddo** [comment]
@KirstenLHDK vi ser os ude af stand til fyldestgørende at kunne svare på spørgsmålet da det har en direkte effekt på hvordan data senere fortolkes i kæden.

**Comment by jkiddo** [comment]
@hagensen-software - måtte du evt. have et hint til dette?

**Comment by KirstenLHDK** [comment]
hej begge @jkiddo og @hagensen-software - der er mig bekendt svaret på spørgsmålet. Jeg foreslår at issuet lukkes, med mindre @MaleneLarsen har invendinger. 

Svaret er sat ind nedenfor: 

Det der er vigtigst er, at man kan se i hvilken tidsperiode, der er blevet leveret noget på en niveau 2 kode. Som jeg forstår den nuværende implementering, kan man enten finde ud af det ved at læse en niveau 2 indsats-periode, eller ved at lægge tidsperioderne for alle de niveau 3 indsatser sammen, som vedrører niveau 2 koden.

Jeg synes umiddelbart at det lyder til at Dedalus har lavet en dobbelt-implementering. Altså både den rene data på niveau 2 - og al detalje-informationen på niveau 3. Jeg tror dog ikke, at det kommer til at betyde, at man kan komme til at dobbelt-tælle, fordi man i forvejen tjekker for overlappende indsatser. Så hermed til mine anbefalinger, som jeg giver uden at kende KLGateways/FLIS/SDS's fortolkning af data, og den medfølgende risiko for at der her tælles to gange selvom der ikke skal. Anbefalingerne er altså udelukkende givet ud fra det perspektiv jeg har som primært er FSIII dokumentationsmetode, FKI og KLGateway indrapportering:

1. period.start er defineret som bevillingstiden, og da bevillingstiden er niveau 2 indsatsens bevillingstid, skal det samme tidspunkt bruges. (hvis vi gerne vil have aktivitetens præcise periode, kan vi på et senere tidspunkt bruge en anden del af FHIR modellen, men da det er ikke besluttet lige nu, mener jeg bevillingstids-feltet skal holdes definitorisk ensartet)
2. Hvis level3 koden afsluttes inden level2 koden (indsatsen) afsluttes må den gerne opdateres med en afslutningstid, det er vist det nemmeste og mest intuitive. Jeg ser dog ikke umiddelbart et problem i at vente med at opdatere den med en afslutningstid, til når niveau-2 indsatsen afsluttes, men jeg har på fornemmelsen at det systemteknisk vil være vanskeligere, og knap så intuitiv for de der skal bruge data.
3. Det er fint, men ikke nødvendigt at lave begge registreringer. Man kunne også have valgt enten at lave de rene niveau-2 indberetninger ELLER udelukkede niveau-3 indberetninger. Sidstnævnte, dog kun så længe I sørger for at der ikke kommer en periode, hvor alle niveau-3 indsatser er afsluttet, selvom niveau 2 indsatsen stadig ikke forstås som afsluttet kommunalt, og der derfor risikere at komme en ny niveau 3 indsats efter nogle dage. KL kigger efter ubrudte tidsperioder, hvor der er leveret noget på niveau 2.

**Comment by hagensen-software** [comment]
> @hagensen-software - måtte du evt. have et hint til dette?

Jeg har ikke myndighed til at definere reglerne, men jeg kan bidrage med de tanker der lå bag specifikationen.

Indberetningen er ikke tænkt til at indrapportere samme data på både niveau 2 og 3. Om data vil blive talt med flere gange afhænger af de forespørgsler som anvenderne af data laver, men det vil være muligt at lave forespørgsler som ikke tæller dobbelt.

Hvis man indberetter data på niveau 3 er det tænkt således for en given niveau 2 ydelse:
- hvis der ikke findes niveau 3 ydelser indberettes niveau 2 ydelsen
- hvis der findes niveau 3 ydelser indberettes disse kun på niveau 3
- hvis der under en niveau 2 ydelse oprettes en niveau 3 ydelse, afsluttes niveau 2 ydelsen og niveau 3 ydelsen oprettes
- tilsvarende hvis en niveau 3 ydelse afsluttes og niveau 2 ydelsen fortsætter afsluttes niveau 3 ydelsen og niveau 2 ydelsen oprettes

**Comment by MaleneLarsen** [comment]
Nej, det er fint - issuet kan godt lukkes. Jeg har modtaget svar på spørgsmålet.
