### ISSUE TITLE
How to gerneate a Subject_token

### ISSUE THREAD

**Issue by LindaLawton** [trifork/klg-docs#5]
[SAML Assertion to JWT Exchange](https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2187362305/SAML+Assertion+to+JWT+Exchange#Obtaining-the-kid-from-a-Public-key)

States that requests for an access token and a refresh token need to contain 

- subject_issuer: The ID of the subject token issuer e.g. kombit-sts.
- subject_token_type: Always urn:ietf:params:oauth:token-type:saml2.
- subject_token: The Base64url encoded SAML Assertion issued by subject_issuer

There no information on the above page with regards to how to create a subject_token.    

# soap web service

Apparently the subject_token must be requested from a web service.   [adgangsstyring-systemer](https://digitaliseringskataloget.dk/l%C3%B8sninger/adgangsstyring-systemer)

The documented web service end point found here does not work

>https://adgangsstyring.eksterntest-stoettesystemerne.dk/runtime/services/trust/14/certificatemixed

It returns a 404.   

# other links

Saml [Trust certifcates](https://digitaliseringskataloget.dk/teknik/certifikater)

**Comment by jvitrifork** [comment]
> There no information on the above page with regards to how to create a subject_token.

-it is issued by Kombit STS. @KirstenLHDK please provide contact details on who to reach out to at Kombit.

**Comment by LindaLawton** [comment]
@jvitrifork  so that you understand the current situation.

I am a Freelance contractor currently working for KMD.  I was given a link to this documentation page to use to authorize these requests to KL Fhir gateway   [SAML Assertion to JWT Exchange](https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2187362305/SAML+Assertion+to+JWT+Exchange#Obtaining-the-kid-from-a-Public-key)     This was all I was given.

I was told to use this forum when I have questions.   

Do you not have any full documentation of the flow for authorization to KL FHIR gateway?   It seams to be missing a lot of pieces.  For example Kombit STS and the whole web service system seams to be missing.

**Comment by jvitrifork** [comment]
Have you seen this page? https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2189361157/Care+Gateway

**Comment by LindaLawton** [comment]
No i have been going from this since may https://build.fhir.org/ig/hl7dk/kl-gateway/

**Comment by jvitrifork** [comment]
https://build.fhir.org/ig/hl7dk/kl-gateway/ describes the content that needs to be sent. https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2189361157/Care+Gateway describes how it can be delivered

**Comment by LindaLawton** [comment]
Yeah as i mentioned the first information i have gotten about authorization was just before Christmas.     Everything prior was just sending the data, there was no information mentioning authorization before that.

I assumed we would need something.

**Comment by jvitrifork** [comment]
This link is also present in the readme: https://github.com/trifork/klg-docs/blob/main/README.md

**Comment by LindaLawton** [comment]
Only got a link to this page after Christmas.

You dont have a newer link for the soap web service do you.    Its still not responding at `https://adgangsstyring.eksterntest-stoettesystemerne.dk/runtime/services/trust/14/certificatemixed`

**Comment by KirstenLHDK** [comment]
Hi, after interaction with KOMBIT, I have the following references: 
For general information  please look at: https://digitaliseringskataloget.dk/kom-godt-i-gang-vejledninger

If @LindaLawton you will need support on STS, KOMBIT recommends to ask at: sts-support@kmd.dk

**Comment by LindaLawton** [comment]
May i ask why this was closed?  the issue still has not be resolved.

**Comment by jvitrifork** [comment]
@LindaLawton I was under the impression that you were blocked by Kombit STS?

**Comment by jvitrifork** [comment]
> I suspect that you were also under the impression that i even knew what Kombit STS was six weeks ago.

No - but it is a prerequisite for using KL Gateway 

> This is your authorization system may i suggest again that you document the flow with an end to end example of this working.

Kombit STS is not our authorization system. That belongs to Kombit.

> Its taken six weeks to find someone to verify that we can not create the subject token using .net as WSTrust is not supported. In .net 6. 

@4TAMU - that is probably useful to you guys to be aware of this.

@LindaLawton I saw that the https://github.com/Serviceplatformen/demoservice-client-net client example implementation was recently updated - however not to .NET 6 - it remains at 4.7.2. I can't say whether that is of use to you.

**Comment by LindaLawton** [comment]
@jvitrifork .Net framework 4.7.2 is EOL in April no one should use it.  It also does not help us as it is pre .Net core which means that it will not run on K8S  So no this upgrade did not help us at all.  This is something I believe I have mentioned time and time again for the last six weeks.   WsTrust packages were deprecated in .Net core they do not work.  Again something i have mentioned serval times over the last serval weeks.

**Comment by jvitrifork** [comment]
It's been a while since I've been doing .NET but looking at https://github.com/dotnet/wcf/blob/main/src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustChannelClientCredentials.cs as well as reading https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/federation-and-issued-tokens it looks like WS trust is supported - also for .NET Core

**Comment by LindaLawton** [comment]
Again we are using .Net 6 multi platform hosted in K8s.

**Comment by jvitrifork** [comment]
How does that pose a problem towards the documentation I linked to?

**Comment by LindaLawton** [comment]
I have spent serval weeks trying to upgrade the .Net sample you gave me for Kombit, there was no way to upgrade the Soap web service part.   

I have tried many things including the Azure WsTrust package and nothing has yet been supported by .Net 6 and can be hosted in K8s.  

If you have a sample I would love to see it.

**Comment by jvitrifork** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/46567685/154263057-6e314c93-f485-4ec9-b8e3-99f746c0334f.png">

I looks pretty kicking and alive to me: https://github.com/dotnet/wcf being the supported on .NET Core

**Comment by jvitrifork** [comment]
Anyways - I'll leave it up to @4TAMU to get the example .NET code updated

**Comment by LindaLawton** [comment]
You understand that .Net 5 and .Net 6 are not the same as .Net Core.  

Are you saying that WCF will run on linux?

**Comment by jvitrifork** [comment]
> You understand that .Net 5 and .Net 6 are not the same as .Net Core.

I think so, yes.

@4TAMU is Anders from Kombit

**Comment by LindaLawton** [comment]
Ok Anders talk to Mads when you read this.   Might save you some time.

**Comment by jvitrifork** [comment]
I can see that I may have misunderstood something between the .NET core and .NET. Thx for pointing that out.

**Comment by LindaLawton** [comment]
Lets see if I can walk though this:

- .Net Framework  1.* - 4.8.*  Windows only  (4.7 is EOL in April)
- .Net Core 1.* - 2.* multi platform mostly.    Things like WPF , WCF and WinForms only work on windows (last one due to System.Drawing).  This also gave us something called .Net Standard 1.* - 2.* which is where everything that's multi platform lives.  As long as you use a libraries that targets .Net standard you can use it multi platform.
- .Net 5, 6 True multi platform everything that wasn't multi platform is gone now.  I think even the new .Net Forms AKA WinForms works multi platform but I need to double check.

Wasn't there some strange versioning with Java a while back as well?   I wont even try to complete with you on Java I have only basic Java understanding.  😁

**Comment by jvitrifork** [comment]
In regards to your analogy:

> You basically told me to go to Aarhus to get a rundstukker. You didnt tell me where Aarhus was. You didnt tell me who to ask for this rundstukker. You didn't even tell me what a rundstukker is. As you can see having systems that are not properly documented makes the life of developers very difficult.

> See my point?

I don’t entirely follow your analogy here but that's okay. I would more see it like the following:

We are saying that you need to deliver a specific parcel to a specific post office (the KL Gateway). The post office will only accept the parcel if you provide it with a stamp from Kombit. The post office itself cannot issue stamps. How you obtain the stamp from Kombit is not of concern of the post office. That is a matter between you and Kombit.

Analogies are notoriously faulty and hard to make and always leave out details so you might not agree with this analogy
