### ISSUE TITLE
Body height validation error and motor function unknown

### ISSUE THREAD

**Issue by kitohe** [trifork/klg-docs#59]
I am testing submitting my report on Test server and I've encountered following issues which I am not sure if I am doing something wrong or if there is some other underlying issue. 

First thing is that when submitting Body Height observation I cannot seem to provide a decimal value, because it fails validation with following error:
`[ERROR] (no details)(further diagnostics: Rule obs-1: 'If height is given as a decimal point number, an error is returned' Failed)`

And the documentation - https://fhir.kl.dk/children/2.0.0/StructureDefinition-klgateway-children-bodyheight.html - says that `obs-1` error is returned when precision is more than one decimal place. This is following part of the report that won't pass validation:

```json
{
      "fullUrl": "Observation/RikkeHeight",
      "resource": {
        "resourceType": "Observation",
        "id": "RikkeHeight",
        "meta": {
          "profile": [
            "http://fhir.kl.dk/children/StructureDefinition/klgateway-children-bodyheight"
          ]
        },
        "status": "final",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs"
              }
            ]
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8302-2"
            },
            {
              "system": "http://snomed.info/sct",
              "code": "1153637007",
              "display": "Body height"
            }
          ]
        },
        "subject": {
          "reference": "Patient/Rikke"
        },
        "encounter": {
          "reference": "Encounter/2mthEncounter"
        },
        "effectiveDateTime": "2020-07-08T12:45:00+02:00",
        "valueQuantity": {
          "value": 39.5,
          "unit": "cm",
          "system": "http://unitsofmeasure.org",
          "code": "cm"
        }
      }
    },
```

Second issue that I am having is that I can't provide a Motor Function observation, as it errors out with following message:
`[ERROR] (no details)(further diagnostics: Profile reference 'http://fhir.kl.dk/children/StructureDefinition/klgateway-children-motor-function' has not been checked because it is unknown)`

This is part of the report that contains this observation:
```json
    {
      "fullUrl": "Observation/RikkeMotorik",
      "resource": {
        "resourceType": "Observation",
        "id": "RikkeMotorik",
        "meta": {
          "profile": [
            "http://fhir.kl.dk/children/StructureDefinition/klgateway-children-motor-function"
          ]
        },
        "status": "final",
        "code": {
          "coding": [
            {
              "system": "http://fhir.kl.dk/term/CodeSystem/FBOE",
              "code": "e04f2ca1-888a-4671-a97a-371b525cd2a3",
              "display": "Motorik"
            }
          ]
        },
        "subject": {
          "reference": "Patient/Rikke"
        },
        "encounter": {
          "reference": "Encounter/2mthEncounter"
        },
        "effectiveDateTime": "2020-07-08T12:45:00+02:00",
        "valueCodeableConcept": {
          "coding": [
            {
              "system": "http://fhir.kl.dk/term/CodeSystem/FBOE",
              "code": "936a0163-08eb-4fdb-bf0c-bcf5bc7cb3f6",
              "display": "Få tegn på udfordret motorik"
            }
          ]
        }
      }
    },
```

**Comment by Kirstinerosenbeck** [comment]
You are using the wrong implementation guide. KLGateway currently runs with version 1.0.0 

You can find it here: https://fhir.kl.dk/children/1.0.0/

Version 1.0.0 does not allow decimal points for height, as you can see here: https://fhir.kl.dk/children/1.0.0/StructureDefinition-klgateway-children-bodyheight.html

Motor function should be reported using this profile: https://fhir.kl.dk/children/1.0.0/StructureDefinition-klgateway-children-indicator.html

**Comment by kitohe** [comment]
Ah, this makes sense now :)

I thought version 2.0.0 is live because of http://fhir.kl.dk/term/history.html. Do you know maybe when v2 will be going live?

**Comment by ohetrifork** [comment]
Version 2.0.0 is not yet planned
