### ISSUE TITLE
Documentation clarification - UTC or UTC+01:00 (Denmark time)?

### ISSUE THREAD

**Issue by LindaLawton** [trifork/klg-docs#6]
[Jwt Payload](https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2187362305/SAML+Assertion+to+JWT+Exchange)

>iat: Issued at - When the token was created. (seconds since UNIX epoch)
>exp: Expiration time - When the token expires (seconds since UNIX epoch)
>nbf: Not valid before - When the token validity starts (seconds since UNIX epoch)

Are these times UTC or UTC+01:00?

**Comment by jvitrifork** [comment]
https://en.wikipedia.org/wiki/Unix_time ->

> The Unix epoch is 00:00:00 UTC on 1 January 1970 (an arbitrary date).

**Comment by LindaLawton** [comment]
I guess I was not clear with my question. I am fully aware that EPOC is UTC.  I am asking what time you would like me to be creating my times in when i convert them to Epoc.

Example of current system time:  I Denmark it is currently 11:11 If I do the following I will get the following results.

>DateTime.Now() the results is 11:11
>DateTime.UTCNow()  the results is 10:11

Doing a Epoc time on each of those will be different.   Try testing it and you will find that epoc on 11:11 is not going to result in the same result as 10:11.   As I hope you can now see this will cause issues if i try to calculate and expiration of 500 seconds as we discussed.   It will either be to long or to short depending upon what you expect my current system time to be calculated from.  ​

Which time would you like me to use?   To denote the current system time on **my** system UTC or UTC+1

I have worked recently with a Danish companies where all dates where expected to be Danish time.   We need to be clear what our time is for creating these.

**Comment by jvitrifork** [comment]
All times are to follow UTC - anything else violates the standard. See https://datatracker.ietf.org/doc/html/rfc7519#section-2 (NumericDate) - which `iat` (https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6), `exp`(https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4) and `nbf` (https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.5) are all based on.

**Comment by LindaLawton** [comment]
Thank you very much.   As you did not link to the RFC section within the comment as is standard with most documentation relating to authorization.  I wanted to be clear and ask.  I do not like assuming things it tends to result in errors.

You may want to add that in your documentation here so that future users of your system will know and not have to bother you with questions.

```
iat: Issued at - When the token was created. (seconds since UNIX epoch)
exp: Expiration time - When the token expires (seconds since UNIX epoch)
nbf: Not valid before - When the token validity starts (seconds since UNIX epoch)
```
