### ISSUE TITLE
kombit serviceaftale

### ISSUE THREAD

**Issue by aonsystematic** [trifork/klg-docs#9]
Hej jeg har oprettet serviceaftale som kombit er ved at kigge på. TIl det spørger de følgende:

Hvorfor er det KOMBIT I tester den med? 
Hvorfor er det med videregivelse af data? 
Hvem fra KOMBIT kender til denne testopstilling?

Er det noget i kan give svar til?

**Comment by nigtrifork** [comment]
@KirstenLHDK kan du svare på det?

**Comment by KirstenLHDK** [comment]
Hej @aonsystematic - mht. det første spørgsmål er det, hvad KOMBIT har anvist, mig bekendt. 
Gatewayen handler om videregivelse af data fra EOJ-systemet via gateway til videre distribution til dataaftagere (KOMBIT FLIS m.fl), ud fra den hjemmel de pågældende har til at modtage data
KOMBIT FLIS er som nævnt modtager af data, samt at projektet har været i dialog med KOMBIT arkitektur. Håber det svarer på spørgsmålene, ellers vend endelig tilbage

**Comment by aonsystematic** [comment]
så nu har jeg lige fået afvist serviceaftalen fra kombit med begrundelsen

"Afvist, da der ikke skal være videregivelse til KOMBIT Kommune."

Jeg fuldte bare instruktionerne jeg var givet her, så hvad er det rigtige, man skal gøre i virkeligheden?
Kan i tage fat i kombit og måske blive enige om hvad vi skal gøre?

**Comment by KirstenLHDK** [comment]
Hej @aonsystematic - vi har talt med KOMBIT og er blevet klogere 

Gatewayløsningen (indberetning) er registreret som serviceudbyder. 
EOJ-systemer, der skal indberette for kommunale kunder har følgende aktiviteter, i første omgang på test:
-	Oprette en serviceaftale med overdragelse, dvs aftaletypen er uden videregivelse 
-	Vælge eget system (EOJ-systemet)
-	Vælge den eller de kommuner, der ønskes serviceaftaler for 
-	Vælge Care Gateway som modtager
-	Angive UUID for de relevante kommuner 
-	Angive rolle (der er pt. én) 

Kommunernes aftaleansvarlige skal godkende anmodningen om serviceaftale. Hvis EOJ-systemet opretter for flere kommuner vil godkendelserne virke på de enkelte kommuner, og der er ikke en afhængighed af, at alle har godkendt.

**Comment by nigtrifork** [comment]
Hej

en lille tilføjelse 

> Angive UUID for de relevante kommuner

Dette udgår. I skal bare vælge kommunerne i listen

> Angive rolle (der er pt. én)

Der er to roller nu
- Care Delivery Reporter (denne udgår)
- Care Delivery Reporter Sytem (denne skal i bruge)

**Comment by aonsystematic** [comment]
Er "Care Delivery Reporter System" aktiv endnu? Jeg har fået lavet og godkendt en serviceaftale ud fra instruktionerne her, men vi kan stadig ikke komme igennem til kombit. Istedet får vi fejl beskeden "The anvendersystem does not have any proper role assignment."

**Comment by nigtrifork** [comment]
@aonsystematic ja, den er aktiv

Jeg har selv oplevet den fejl du får. Årsagen var at jeg brugte det forkerte cvr nummer.

**Comment by aonsystematic** [comment]
Det tror jeg ikke er tilfældet hos os, da jeg godt kan få adgang til andre kombit services.
Kan i muligvis give et screenshot af jeres konfiguration, så jeg kan sammenligne med den vi har lavet?

**Comment by nigtrifork** [comment]
![image](https://user-images.githubusercontent.com/43570675/154441936-d0f27ff5-76fa-4be7-b06b-949d5c7be61b.png)

Vi anvender her hillerød kommunes cvr når vi kalder kombit sts

**Comment by MikaelKorsgaard** [comment]
@nigtrifork Jeg er ved at oprette en serviceaftale på admin-test.serviceplatformen.dk for Nexus (KMD) data, og jeg er lidt forvittet over dit eksempel (screenshot), hvor "Hillerød Kommune" står som datamodtager. 

I har tidligere skrevet, at aftaletypen er "Med videregivelse af data, én dataejer og én datamodtager" og at "Data owner should be the municipality, data receiver should be Kombit" (https://github.com/trifork/klg-docs/issues/2).

Så, jeg har oprettet nedenstående, men det er øjensynligt ikke rigtigt?

![image](https://user-images.githubusercontent.com/84853446/155113572-701490f5-8b0e-4005-bbbf-c3ceeff6a807.png)

**Comment by KirstenLHDK** [comment]
@nigtrifork - jeg har fortalt Mikael, at det er kommunen, der skal være modtager og at det ikke er en aftale om videregivelse - hvis der er mere at tilføje er du meget velkommen :-)

**Comment by MikaelKorsgaard** [comment]
@KirstenLHDK  @nigtrifork Tak. Vores eneste udestående er nu umiddelbart, at vi mangler client id (se mit pull request fra i går), for at vi kan teste.

**Comment by nigtrifork** [comment]
@MikaelKorsgaard Den er klar til jer nu. se kommentar på #12

**Comment by MikaelKorsgaard** [comment]
@nigtrifork Tak! Vi prøver.

**Comment by jkiddo** [comment]
@MikaelKorsgaard kan sagen lukkes?

**Comment by MikaelKorsgaard** [comment]
@jkiddo Ja. Tak. Vi er videre fra det issue.

**Comment by jkiddo** [comment]
@aonsystematic - gælder det også dig?

**Comment by aonsystematic** [comment]
sagen kan godt lukkes for min skyld
